// Command jotawm-keybinds is a small always-on-top popup that shows
// jotawm's keybinds, read from its README.md at build time. It closes as
// soon as it loses focus, the user clicks outside of it, or presses any
// key.
package main

import (
	"fmt"
	"os"

	"github.com/jezek/xgb/xproto"
	"github.com/jezek/xgbutil"
	"github.com/jezek/xgbutil/keybind"
	"github.com/jezek/xgbutil/xinerama"
	"github.com/jezek/xgbutil/xwindow"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "jotawm-keybinds:", err)
		os.Exit(1)
	}
}

func run() error {
	X, err := xgbutil.NewConn()
	if err != nil {
		return fmt.Errorf("connecting to X: %w", err)
	}
	defer X.Conn().Close()

	keybind.Initialize(X)

	font, err := loadFont()
	if err != nil {
		return err
	}

	kb := loadKeybinds()
	img := renderImage(X, kb, font)

	x, y := popupPosition(X)

	win, err := xwindow.Generate(X)
	if err != nil {
		return fmt.Errorf("allocating window id: %w", err)
	}

	eventMask := uint32(xproto.EventMaskFocusChange | xproto.EventMaskKeyPress | xproto.EventMaskButtonPress)
	win.Create(X.RootWin(), x, y, WindowWidth, WindowHeight,
		xproto.CwOverrideRedirect|xproto.CwEventMask,
		1, eventMask)

	img.XSurfaceSet(win.Id)
	img.XDraw()
	img.XPaint(win.Id)

	win.Map()
	win.Stack(xproto.StackModeAbove)

	pointerGrabbed := grabPointer(X, win.Id)
	keyboardGrabbed := keybind.GrabKeyboard(X, win.Id) == nil
	if !keyboardGrabbed {
		xproto.SetInputFocus(X.Conn(), xproto.InputFocusParent, win.Id, xproto.TimeCurrentTime)
	}

	defer func() {
		if pointerGrabbed {
			xproto.UngrabPointer(X.Conn(), xproto.TimeCurrentTime)
		}
		if keyboardGrabbed {
			keybind.UngrabKeyboard(X)
		}
	}()

	return eventLoop(X)
}

// popupPosition centers the popup on the Xinerama head containing the
// mouse pointer, falling back to the root window's geometry if Xinerama
// info isn't available.
func popupPosition(X *xgbutil.XUtil) (int, int) {
	rootW := int(X.Screen().WidthInPixels)
	rootH := int(X.Screen().HeightInPixels)
	originX, originY := 0, 0
	areaW, areaH := rootW, rootH

	if heads, err := xinerama.PhysicalHeads(X); err == nil && len(heads) > 0 {
		ptr, err := xproto.QueryPointer(X.Conn(), X.RootWin()).Reply()
		if err == nil {
			for _, h := range heads {
				if int(ptr.RootX) >= h.X() && int(ptr.RootX) < h.X()+h.Width() &&
					int(ptr.RootY) >= h.Y() && int(ptr.RootY) < h.Y()+h.Height() {
					originX, originY = h.X(), h.Y()
					areaW, areaH = h.Width(), h.Height()
					break
				}
			}
		}
	}

	return originX + (areaW-WindowWidth)/2, originY + (areaH-WindowHeight)/2
}

func grabPointer(X *xgbutil.XUtil, win xproto.Window) bool {
	reply, err := xproto.GrabPointer(X.Conn(), false, win,
		xproto.EventMaskButtonPress,
		xproto.GrabModeAsync, xproto.GrabModeAsync,
		0, 0, xproto.TimeCurrentTime).Reply()
	return err == nil && reply != nil && reply.Status == xproto.GrabStatusSuccess
}

// eventLoop blocks until the popup should close: on losing input focus, on
// any key press, or on a button press outside of the popup's own bounds.
func eventLoop(X *xgbutil.XUtil) error {
	for {
		ev, xerr := X.Conn().WaitForEvent()
		if xerr != nil {
			return fmt.Errorf("X protocol error: %w", xerr)
		}
		if ev == nil {
			return nil
		}

		if os.Getenv("JOTAWM_KEYBINDS_DEBUG") != "" {
			fmt.Fprintf(os.Stderr, "event: %#v\n", ev)
		}

		switch e := ev.(type) {
		case xproto.FocusOutEvent:
			// Ignore the synthetic FocusOut/FocusIn pairs generated by our
			// own active pointer/keyboard grabs below; only a genuine
			// focus change (NotifyModeNormal) means the popup lost focus.
			if e.Mode == xproto.NotifyModeNormal {
				return nil
			}

		case xproto.KeyPressEvent:
			return nil

		case xproto.ButtonPressEvent:
			if e.EventX < 0 || e.EventY < 0 ||
				int(e.EventX) >= WindowWidth || int(e.EventY) >= WindowHeight {
				return nil
			}
		}
	}
}
